# Foundations

We begin with some foundational material that forms the basis of all applied mathematics.

## Numbers

We deal with various number systems in mathematics.

* The set of *natural numbers* are the familiar counting numbers:
    $$1, 2, 3,\dotsc$$
    We denote these by the symbol $\mathbb{N}$.

* The *integers* are the "whole numbers", which include zero and negative numbers:
    $$\dots,-2,-1,0,1,2,\dots$$
    We denote these by the symbol $\mathbb{Z}$.

* We sometimes want to focus on just the *positive integers*, which is another name for the natural numbers.

* The *non-negative integers* are the numbers:
    $$0, 1, 2, 3,\dotsc$$
    (the natural numbers and zero).

* The *negative integers* are the numbers:
    $$-1, -2, -3,\dotsc$$

* The *rational numbers* are numbers which can be written in the form $\frac{a}{b}$ where $a$ and $b$ are integers, with $b\neq 0$, so numbers like
    $$\frac{1}{2}, \frac{3}{2}, -\frac{4}{5}, \dotsc$$
    Note these include the integers since they can be written as $\frac{a}{1}$. Rational numbers are denoted $\mathbb{Q}$.

* The ancient Greeks discovered that there are numbers that are not rational -- so-called *irrational numbers*. For example, $\sqrt{2}, \pi$ and $e$ are all irrational numbers. One way of characterising irrational numbers is that they have a decimal representation that never repeats...
    $$
    \pi=3.141592653589793238462643383279502884197169399375105820\dots
    $$
    In contrast, all rational numbers have an eventually repeating decimal expansion (after perhaps some initial jumble of digits, there is a repeating pattern), for example:
    
    |Rational Number| Repeating pattern|
    |---|---|
    |$\frac{1}{3}=0.333\dots$|repeating $3$'s|
    |$\frac{3}{2}=1.5000\dots$|repeating $0$'s after the first decimal digit, which we normally don't write down!|
    |$\frac{219}{1750}=0.125142857142857\dots$|repeating sequence $142857$ of length $6$ after the first $3$ decimal digits|    

* The *real numbers* consist of all rational and irrational numbers together
    We can think of real numbers as points on a continuous straight line, or as numbers that possibly have a decimal representation requiring an infinite number of digits^[Real numbers require quite a bit of work to define in a rigorous mathematical way and we will not do this here; the interested reader should look up "construction of real numbers by Dedekind cuts" or "construction of real numbers by Cauchy sequences".].
    The set of real numbers is denoted by $\mathbb{R}$.

* We learn about all of the above numbers early on in our mathematical education. However, there is a further set of numbers that is very useful in science and engineering that you may not have encountered before: the *complex numbers*, denoted by $\mathbb{C}$. These are not as intuitive as real numbers and we explore them in detail in section \@ref(complex).


## Algebra

This section contains some basic algebraic rules. Fluency with notation and manipulations allows us to progress to higher level mathematics with ease.

We are familiar with the basic rules of arithmetic: $+, -, \times, \div$. When an expression contains multiple operations we can use brackets to indicate the order in which the operations are executed. We also commonly use powers (exponents). When evaluating an expression, remember to use the mnemonic BEDMAS, which defines the precedence of these operations:

B - Brackets

E - Exponents

D - Division

M - Multiplication

A - Addition

S - Subtraction

Division and Multiplication can be carried out in either order, as can Addition and Subtraction. We'll recap the rules of Brackets and Exponents in the next sections.

:::{.example name="BEDMAS" #BEDMAS}
We have
$$3+2\times 4=11,$$
whilst
$$(3+2)\times 4 = 20.$$
:::

### Rules of Exponents {#exponents}

In their most basic form, we use exponents as a shorthand for multiplication of a number by itself some positive integer number of times. For example:

$5\times 5 = 5^2$ spoken as "5 squared"

$5\times 5\times 5=5^3$ spoken as "5 cubed"

and more generally, for any real number $x$ and positive integer $n$,
$\underbrace{x\times \dotsb \times x}_{\text{with }n\, x\text{'s}} = x^n$ spoken as "x to the power $n$"

The number $x$ is known as the *base* and the number $n$ is known as the *power*, *index* or *exponent*.

Now for any real number $x$ and positive integers $a$ and $b$, it should be clear that the following rule holds:

::: {.theorem #exprule1 name="Rule 1"}
$$x^ax^b=x^{a+b}$$
:::

since we are multiplying $a$ $x$'s by a further $b$ $x$'s to give a total of $a+b$ $x$'s multiplied together. Extending this idea, we also have:

::: {.theorem #exprule1 name="Rule 2"}
$$(x^a)^b=x^{ab}$$
:::

::: {.exercise #rule2}
Why does Rule 2 hold? Can you prove it using Rule 1? Furthermore, show that $(x^a)^b=(x^b)^a$.
:::

So far we have allowed the exponents to be positive integers. Can we make sense of negative integers as exponents? Consider for $a$ and $b$ as positive integers the product

$$x^a\frac{1}{x^b}=\frac{x^a}{x^b}$$

For arguments sake let's take $a>b$, then since we have $a$ $x$'s on the top and $b$ $x$'s on the bottom, we can cancel the common factors to leave $a-b$ $x$'s. So,

\begin{equation}
x^a\frac{1}{x^b}=\frac{x^a}{x^b}=x^{a-b} (\#eq:divexps)
\end{equation}

and following Rule 1 we could think of this as $x^{a-b}=x^{a+(-b)}=x^ax^{-b}$, and therefore using a negative exponent $-b$ gives the reciprocal of $x^b$

::: {.theorem #exprule1 name="Rule 3"}
$$x^{-a}=\frac{1}{x^a}$$
:::

Next, we can consider the value of $x^0$. In \@ref(eq:divexps) with the particular case $b=a$, we have

$$1=\frac{x^a}{x^a}=x^{a-a}=x^0$$

so we get that for any non-zero^[We need to be more careful when $x=0$, since we would have $\frac{0^a}{0^a}=\frac{0}{0}$, which is an indeterminate form so the argument is not valid; it turns out $0^0$ is also an indeterminate form.] value of $x$ 

::: {.theorem name="Rule 4"}
$$x^0=1$$
:::

Now lets try to make sense of a power of the form $x^{\frac{a}{b}}$ where $a$ is an integer and $b$ is a positive integer. That is, we now allow for fractional (otherwise known as *rational*) exponents. Since we have $\frac{a}{b}=a\frac{1}{b}$ we can write (using Rule 2):

$$x^{\frac{a}{b}}=(x^a)^{\frac{1}{b}}.$$

In the case $b=a$, we therefore have

$x=x^1=x^{\frac{a}{a}}=(x^{\frac{1}{a}})^a$.

This means that raising $x^\frac{1}{a}$ to the power $a$ gets us back to $x$, hence the number $x^\frac{1}{a}$ is the $a$^{th} root of $x$. For example $(3^\frac{1}{2})^2=3^{2\frac{1}{2}}=3^1=3$, so we must have $3^\frac{1}{2}=\sqrt{3}$.

::: {.theorem name="Rule 5"}
$$x^{\frac{1}{a}}=\sqrt[n]{x}.$$
:::

In particular the square root is $x^{\frac{1}{2}}=\sqrt{x}$ and the cube root is $x^{\frac{1}{3}}=\sqrt[3]{x}$; we tend to use the root notation for expressions containing square or cube roots on their own, and use the power notation when combining different roots.

It turns out that we can extend exponents beyond rational numbers to any *real* number, with all of the above rules still holding. Proving this is beyond the scope of these notes, but the interested reader can easily find out more about this in a textbook or online.

Something's missing: we said $x$ can be any real number, but then how do we interpret something like $y=(-1)^\frac{1}{2}$? That is, $y$ must be a number such that when it is multiplied by itself it gives the negative number $-1$, but this is impossible for a real number! Answering this conundrum requires us to invent a new set of numbers, called *complex numbers* -- see section \@ref(complex).


A summary of the rules:

::: {.theorem #exprules name="Rules of Exponents"}

1. $x^ax^b=x^{a+b}$
2. $(x^a)^b=x^{ab}$
3. $x^{-a}=\frac{1}{x^a}$
4. $x^0=1$
5. $x^{\frac{1}{a}}=\sqrt[n]{x}.$
:::


### Brackets

We use brackets to set the precedence (or order) of evaluating the different parts of an expression. We evaluate the innermost brackets first. Note we usually omit the multiplication sign when multiplying a bracketed expression.

::: {.example name="brackets"}
$$5(((2+4)\div (5-2))+1)=5((6\div 3)+1)=5(2+1)=5\times 3 = 15$$
:::

Sometimes you might find it helpful to add "redundant" brackets to make the calculation clearer. For example, we could write
$$3+2\times 4=11$$
as
$$3+(2\times 4)=11.$$
The brackets are not really needed in the second version, since we get the same result from following BEDMAS, but adding brackets can make an expression easier to read and evaluate.

#### Expansion
Recall that we can expand expressions involving multiplication of brackets such as the following:

$$a(b+c)=ab+ac$$
$$(a+b)(c+d)=ac+ad+bc+bd$$
$$(a+b)^2=(a+b)(a+b)=a^2+ab+ba+b^2=a^2+b^2+2ab$$
$$(ab)^2=(ab)(ab)=a^2b^2$$

We often want to expand expressions in order to simplify them by grouping together like-terms, for example:

$$(a+b)(b+c)+2ac=ab+ac+b^2+bc+2ac=ab+3ac+b^2+bc$$

In the case of the sum of two numbers (a *binomial* term) to a postive integer power, i.e. something of the form

$$(a+b)^n$$

which involves multiplying out the brackets $n$ times, we have a general formula for the expansion. We start by looking at a slightly simpler form
$$(1+x)^n$$

Let's take a look at the expansion for the first few values of $n$.

$n=0:$ $(1+x)^0 = 1$

$n=1:$ $(1+x)^1=1+x$

$n=2:$ $(1+x)^2=(1+x)(1+x)=x^2+2x+1$

$n=3:$ $(1+x^3)=(1+x)(1+x)^2=(1+x)(x^2+2x+1)=x^3+3x^2+3x+1$

The coefficients of $x$ form the $n^\text{th}$ row of Pascal's triangle.

The general formula is:

$$(1+x)^n = \binom{n}{0}x^0+\binom{n}{1}x^1+\binom{n}{2}x^2+\dotsb+\binom{n}{n-1}x^{n-1}+\binom{n}{n}x^n$$

where $\binom{n}{k}$ is the binomial coefficient

$$\binom{n}{k}=\frac{n!}{k!(n-k)!}$$

and $n!$ is the *factorial* of $n$:

$$n!=n\times(n-1)\times(n-2)\times\dotsb \times3\times 2\times 1$$.

Given the more general form $(a+b)^n$, we can first extract a factor of $a$ to give

$$(a+b)^n=(a(1+\frac{b}{a}))^n=a^n(1+\frac{b}{a})^n$$

so we now just need to evaluate $(1+\frac{b}{a})^n$ using the formula and substituting $x$ with $\frac{b}{a}$. Alternatively, the full formula is:

$$(x+y)^n = \binom{n}{0}x^ny^0+\binom{n}{1}x^{n-1}y^1+\binom{n}{2}x^{n-2}y^2+\dotsb+\binom{n}{n-1}x^1y^{n-1}\binom{n}{n}x^0y^n.$$

#### Factorisation

At other times, we wish to simplify by extracting common factors from an expression, which we call *factorisation*. In the simplest form, this could just be factorising a single number

$$2x+2y=2(x+y)$$

Or, it could involve extracting more complicated factors, for example

$$2xy+6x^2y=2xy(1+3x)$$
$$x^2-3x-10=(x+2)(x-5)$$

The second example here is *factorising a quadratic* which we can do systematically by finding the roots -- we will see how to do this later in section XYZ


### Simplifiying Expressions

In order to simplify an expression we can carry out the following proceedures:

* Expand brackets
* Collect together any like-terms, e.g. $2a+3b+a=3a+3b$, $a^3a^2+b^2=a^5+b^2$
* Simplify any fractions: use common denominators, e.g. $\frac{a}{b}+\frac{c}{d}=\frac{da+bc}{bd}$;  cancel any common factors, e.g. $\frac{ab}{ac}=\frac{b}{c}$
* Factorise

Note: these are "rules of thumb", as there usually does not exist such a thing as a "simplest" form for a given algebraic expression. The meaning of "simple" is dependent on what we want to gain from it. The intention is to put the expression in a form that is easier to understand (in the given context) and which usually uses fewer symbols (but not always).

