# Exercise Set 1 {-}

These exercises cover the topics of Algebra, Equations and Inequalities.  

1. Simplify each of the following (*Hint*: use the rules of exponents where needed).
    a. $x = 3pq+5pr=2qr+qp-6rp$
    a. $y = 5l^2mn+2nl^2m-3mln^2+l^2nm+4n^2ml-nm^2$
    a. $z = \frac{(s^\frac{1}{3})^\frac{3}{4}\times (t^\frac{1}{4})^{-1}}{(t^\frac{1}{2}\times (s^{-\frac{1}{4}})^{-1})}$  

1. Expand the brackets in each of the following and simplify the expression.
    a. $-4x(2x-y)(3x+2y)$
    a. $(a-2b)(2a-3b)(3a-4b)$
    a. $-\{-2[x-3(y-4)]-5(z+6)\}$
    a. $(v^3-v^2-2)(1-3v+2v^2)$  

1. Simplify each of the following.
    a. $\frac{p}{q^3}\div\frac{p^3}{q}$
    a. $\frac{a^2b}{2c}\times\frac{ac^2}{2b}\div\frac{b^2c}{2a}$
    a. $\frac{8x^{-3}\times 3x^2}{6x^{-4}}$
    a. $\frac{3x}{3x^2+6x}$  

1. Factorise the following expressions.
    a. $18x^2y-12xy^2$
    a. $x^3+4x^2y-3xy^2-12y^3$
    a. $25x^2-4y^2$
    a. $3x^2-14x+8$
    a. $x^2+10x+25$  

1.  The characteristic equation of a perfect gas is given by $P V = mRT$ where $m$ is the mass, $P$ is the pressure, $V$ is the volume, $T$ is the temperature and $R$ is the universal gas constant. Make temperature the subject of the formula.  

1.  The airflow over a turbine blade causes drag $D$, which is given by $D= \frac{\rho C v^2 A}{2}$, where $\rho$ is fluid density, $C$ is the drag coefficient, $v$ is fluid velocity and $A$ is the frontal area of the blade. Make the frontal area the subject of the formula.  

1. Make $b$ the subject of the following formula.
    $$W=\frac{t\sqrt{a+b^2}}{2\pi}$$  

1. Solve the following quadratic equations by factorisation.
    a. $x^2-28x-60=0$
    a. $p^2=8p-15$
    a. $-2y^2(3+y^2)=(2y^2+2y-3)(-y^2+y-4)-2$  

1. Solve the following quadratic equations, giving results correct to 2 d.p.
    a. $4x^2+x-3=0$
    a. $x^2+x=5$
    a. $x+\frac{1}{x}=5$  

1. Solve the following sets of simultaneous equations.
    a. $3x+4y=7$, $5x+6y=11$
    a. $2x+y=7$, $x^2-xy=6$
    a. $x + y=2$, $x^2-xy+y^2 = 1$  

1. Solve the following inequalities.
    a. $7-3x>x-5$
    a. $x^2\ge 4$
    a. $x^2-x-6<0$
    a. $x^2-3x-12\le 2x+2$
    a. $\frac{2}{2x-1} > \frac{3}{3x+1}$
    a. $\frac{2x}{x-5}\le 3$
    a. $x^3-9x^2<0$  
    