# Sequences


A *sequence* is an ordered list of objects (usually numbers, but also vectors, matrices or any other mathematical object). It may be finite or infinite. Some sequences of numbers:


* A finite sequence: $2, 4, 6, 8$
* Square numbers:  $1, 4, 9, 16,\dotsc$
* Fibonacci: $0, 1, 1, 2, 3, 5, 8, 13, 21, 34,\dotsc$
* What comes next?: $1, 11, 21, 1211, 111221, 312211,\dotsc$ (the "look-and-say'' sequence)

We write
\begin{align*}
(a_n)&_{n=1}^{\infty}\quad\text{or simply}\quad(a_n)\quad\text{for the infinite sequence of numbers }a_1,a_2,a_3,\dotsc\\
&\big\uparrow_\text{read as ''from $n$ equals $1$ to infinity''}
\end{align*}

We say that the number $a_1$ is the *first term* of the sequence, $a_2$ the *second term* etc. and $a_n$ is a general term of the sequence -- the *$n^\text{th}$ term*. Note that a sequence of real numbers can also be viewed as a function from the natural numbers to the real numbers with $f(n)=a_n$.

Two ways of specifying the terms of a sequence are:
1. By a formula for each term depending on $n$, e.g.
$$
a_n=n^2-1\quad\text{corresponding to the sequence}\quad 0,3,8,15,24,\dotsc
$$
\item By a *recursive forumla*, i.e. a formula that depends on previous terms in the sequence, e.g. the Fibonacci sequence can be defined by $F_1=0,F_2=1$ together with
$$
F_n=F_{n-1}+F_{n-2}\qquad\text{for }n>2
$$



Two commonly encountered forms of sequences are *arithmetic* sequences and *geometric* sequences.

An arithmetic sequence is given by a formula of the form
$$a_n=a+(n-1)d$$
where $a$ is the first term and $d$ is the common difference.
For example,
$$4,7,10,13,\dotsc$$
is given by the formula
$$a_n=4+(n-1)3.$$

A geometric sequence is given by a formula of the form
$$a_n=ar^{n-1}$$
where $a$ is the first term and $r$ is the common ratio.
For example,
$$2, 1, \frac{1}{4}, \frac{1}{8},\dotsc$$
is given by the formula
$$a_n=2\times \left(\frac{1}{2}\right)^{n-1}.$$

## Limits of Sequences

Consider the sequence defined by the following formula:
$$
a_n=\frac{n}{n+1}.
$$
The first three terms are
$$
a_1=\frac{1}{2},\quad a_2=\frac{2}{3},\quad a_3=\frac{3}{4}.
$$
The terms corresponding to $n=100,101,102$ are
$$
a_{100}=\frac{100}{101},\quad a_{101}=\frac{101}{102},\quad a_{102}=\frac{102}{103}
$$
which are close to $1$, for example $\frac{100}{101}$ is different to $1$ by just $\frac{1}{101}$. We can see that as $n$ grows, $a_n$ becomes closer and closer to the value $1$; we say that the sequence $\{a_n\}_{n=1}^\infty$ has *limit* $1$.

Intuitively a sequence has a limit $L$ if its terms get closer and closer to $L$. More mathematically we say that a sequence $(a_n)$ *converges* to a limit $L$ if $a_n$ is "close to" $L$ "for all large positive integers $n$". We give a formal mathematical definition below.

The following examples introduce some more terminology.

The *harmonic sequence*
$$
1, \frac{1}{2}, \frac{1}{3},\dotsc
$$
defined by the formula
$$
a_n=\dfrac{1}{n}
$$
is continually decreasing and converges to zero.

The Fibonacci sequence does not converge to a limit and keeps growing without bound
$$
0, 1, 1, 2, 3, 5, 8, 13, 21, 34,\dotsc
$$
If a sequence does not converge we say that it *diverges*. Because this sequence continues to grow we say it *diverges to infinity*.

The sequence
 $$
 a_n=(-1)^{n+1}
 $$
 has terms $1,-1,1,-1,1,\dotsc$ and does not converge to a single value; because it does not converge it *diverges*, but because it does not simply grow to $+\infty$ or $-\infty$ we say that it \textit{oscillates}.

The formal definition of a limit for a sequence is:

::: {.definition #label name="definition name"}
Let $(a_n)_{n=1}^{\infty}$ be a sequence of real numbers. We say that the sequence has *limit* $L$ if for every $\varepsilon>0$ there exists a positive integer $N$ such that if $n\geq N$ then
$$
	\left|a_n-L\right|<\varepsilon.
$$
:::

This definition works as follows: by choosing a small value for $\varepsilon$ we set how close the terms of the sequence need to be to $L$ and the definition then says we must be able to find an integer $N$ such that all terms of the sequence $a_n$ for $n\geq N$ (i.e. the values $a_N,a_{N+1},a_{N+2},\dotsc$) are within $\varepsilon$ of $L$; we then need to be able to do this for any value of $\varepsilon$ -- this is how we formally state that the terms must be getting closer to $L$. (The Greek lower-case letter epsilon $\varepsilon$ is commonly used to denote a "small" number in mathematics.)

If the sequence $(a_n)_{n=1}^{\infty}$ has limit $L$, we write
$$
	\lim\limits_{n\to\infty}a_n=L
$$
read as "the limit of $a_n$ as $n$ approaches infinity is $L$", or alternatively
$$
	a_n\to L\text{ as }n\to\infty
$$
read as "$a_n$ tends to the limit $L$ as $n$ tends to infinity".

Note that for any arithmetic sequence $a_n=a+(n-1)d$ we have:

* $d>0$: divergence to $\infty$;
* $d=0$: convergence to $a$ (all terms are $a$);
* $d<0$: divergence to $-\infty$.

For geometric sequences $a_n=ar^n$ with $a\neq 0$ we have:

* $r>1$: divergence to $\infty$ if $a>0$, or $-\infty$ if $a<0$;
* $r=1$: convergence to $a$ (the constant sequence with all terms $a$);
* $-1 < r < 1$: convergence to $0$ (the constant sequence with all terms $0$ in the case $r=0$);
* $r\leq-1$: an oscillating sequence.

