# Exercise Set 2 Answers {.unlisted .unnumbered}

These exercises cover the topics of Functions and Graphs.

1. Sketch the graphs of the following functions on the interval $-2\le x \le 2$.
    a. $y=-\frac{1}{2}(x+1)$
    a. $y=x^2+2$
    a. $y=-2x^2+2$
    a. $y=x^2-x-1$
    a. $y=3^x$
    a. $y=\frac{1}{x}$

    Tips: find where the functions cross the axes; use completing the square to find the maximum or minimum of quadratics; identify any asymptotes.

    Answers:
    a. Expanding: $y=-\frac{1}{2}x-\frac{1}{2}$ which we recognise as a line with gradient $-\frac{1}{2}$ and y intercept $-\frac{1}{2}$. Solving for $y=0$ gives the x intercept as $(-1,0)$.
    a. This is a parabola shifted up by 2 units.
    a. This is an "upside down" parabola, shifted up by two units.
    a. Completing the square: $y=(x - \frac{1}{2})^2 - \frac{5}{4}$
        Since the squared term is always non-negative, it is smallest when it is zero at $x=\frac{1}{2}$. This is the position of the minimum, and at this point $y=-\frac{5}{4}$.
        Factorising: $(x-\frac{1+\sqrt{5}}{2})(x-\frac{1-\sqrt{5}}{2})$, so the curve crosses the x axis at $x=\frac{1+\sqrt{5}}{2}$ and $x=\frac{1-\sqrt{5}}{2}$. Since the coefficient of $x^2$ is positive, the parabola opens upwards.
    a. This is an exponential $a^x$ with $a>1$. All exponential functions cross the y axis at $a^0=1$ and the do not cross the $x$ axis.
    a. This is a rational function with a vertical asymptote at $x=0$. It is small and positive for large positive values of $x$ and it is small and negative for large negative values of $x$: the line $y=0$ is a horizontal asymptote.

1. Sketch the following graphs (with $x$ in radians):
    a. $y=\sin(x)$
    a. $y=\sin(x+\frac{\pi}{2})$ (does this look familiar?)
    a. $y=\sin(2x)$
    a. $y=\sin^2(x)$

    Answers:

    a. You should be familiar with this graph.
    a. Note that $\sin(x+\frac{\pi}{2})=\cos(x)$.
    a. This is double the angular frequency.
    a. Note that all the y values are non-negative.

1. If we had the graph of a function $f(x)$, describe what would change qualitatively for the graph of $f(a\times x)$ where $a$ is a constant. Consider the cases:
    a. $a>1$
    a. $0 < a < 1$
    a. $-1 < a < 0$
    a. $a<-1$

    Answers:

    a. For $a>1$, the graph is `squeezed' along the x axis, with the value at $x=0$ remaining unchanged.
    b. For $0 < a <1$, the graph is expanded along the x axis, again with the value at $x=0$ unchanged.
    c. For $-1 < a <0$, the graph is again expanded, along the x axis, but the minus sign in $a$ also means that the graph is reflected in the y axis.
    d. For $a<-1$, the graph is squeezed horizontally and reflected in the y axis.

 1. If we had the graph of a function $f(x)$, describe what would change qualitatively for the graph of $f(x+b)$ where $b$ is a constant. Consider the cases:
    a. $b>0$
    a. $b<0$

    Answers:

    a. For $b>0$, the $f(x+b)$ is the graph of $f(x)$ translated to the left by distance $b$
    b. For $b<0$, the whole graph is translated to the right by distance $b$


 1. If we had the graph of a function $f(x)$, describe what would change qualitatively for the graph of $f(x)+c$ where $c$ is a constant. Consider the cases:
    a. $c>0$
    a. $c<0$
    
    
    Answers:
    a. For $c>0$, $f(x)+c$ is the graph of $f(x)$ shifted vertically up along the y axis
    b. For $c<0$, $f(x)+c$ is the graph of $f(x)$ shifted vertically down along the y axis

1. Find the solutions to the following equations without using a calculator.
    a. $x=\log_4(64)$
    a. $x=\log_{101}(101)$
    a. $x=\ln(e)$
    a. $x=\log_{56}(1)$
    a. $10^x=100000$
    a. $2^x=128$
    a. $\log_3(x)=4$
    a. $\log_x(125)=3$
    
    
    Answers:
    a. $x = \log_4(64) = \log_4(4^3)=3$
    b. $x = \log_{101}(101) =\log_{101}(101^1)=1$
    c. $x = \ln(e) =\log_e(e^1)= 1$
    d. $x = log_{56}(1) =\log_{56}(56^0)=0$
    e. $10^x = 100000=10^5$ \Rightarrow x = 5$
    f. $2^x = 128=2^7$ \Rightarrow x = 7$ the powers of 2 are useful to know
    g. $3^{\log_3(x)} = 3^4 \Rightarrow x = 3^4 = 3^2 \times 3^2 = 81$
    h. $\log_x(125) = 3 \Rightarrow x^3 = 125 \Rightarrow x = 5$


1. Calculate the following logarithms using a calculator.
    a. $\ln(2)$
    a. $\log(20)$
    a. $\log_{16}(100)$ - do this using your $\log_a(x)$ button and also using the change of base rule with your $\log$ or $\ln$ button.

    Answers:
    To 2 d.p.
    a. $\ln(2) = 0.69$
    b. $\log(20) = 1.30$
    c. $\log_{16}(100) = 1.66$ or using the change of base rule with $\log_{10}$, $\log_{16}=\frac{\log_{10}(100)}{\log_{10}(16)}=\frac{2}{\log_{10}(16)}=1.66$

1. Calculate $4321\times 9876$ using logs: convert both values to logs, add, then convert back.

Answer:
$$\log(4321 \times 9876)=\log(4321) + \log(9876) = 7.630165..., \text{ the product rule of logarithms}\\
4321 \times 9876=10^{7.630165...} = 42674196
$$

1. Simplify the following expression involving logarithms.
     $$\log_a(x^2)+3\log_a(x)-2\log_a(4x^2).$$

Answer:
Applying the various log rules, starting with the power rules then product and quotient rules:
$$
\begin{aligned}
& \log_a(x^2)+3\log_a(x)-2\log_a(4x^2)\\
&= \log_a(x^2) + \log_a(x^3) - log_a(16x^4)\\
&= \log_a(\frac{x^5}{16x^4})\\
&= \log_a(\frac{x}{16})
\end{aligned}
$$


1. Solve the following for $x$.
    $$2\log_a(x)-\log_a(x-1)=\log_a(x+3).$$

Answer:
$$
\begin{aligned}
2 \log_a(x) - \log_a(x-1) &= \log_a(x+3)\\
\log_a\left(\frac{x^2}{x-1}\right) &= \log_a(x+3)\\
\log_a\left(\frac{x^2}{(x-1)(x+3)}\right) &= 0, \text{ since } \log_a(1) = 0\\
\frac{x^2}{(x-1)(x+3)} &= 1\\
x^2 &= (x-1)(x+3) = x^2 + 2x - 3\\
x &= \frac{3}{2}
\end{aligned}
$$

1. Find $y$ in terms of $x$:
    $$5\log_a(y)-2\log_a(x+4)=2\log_a(y)+\log_a(x).$$

Answer:
First, rearrange and then apply the logarithm power, product and quotient rules:
$$
\begin{align}
5\log_a(y)-2\log_a(x+4)&=2\log_a(y)+\log_a(x)\\
\Rightarrow \log_a(y^5) - \log_a(y^2) &= \log_a(x) + 2\log_a(x+4)\\
= \log_a(y^3) &= \log_a((x+4)^2)\\
\Rightarrow y^3 &= x(x+4)^2\\
y &= \left(x(x+4)^2\right)^{\frac{1}{3}}
\end{align}
$$

1. Use natural logarthims to make $t$ the subject of the formula
    $$V=1-e^{\frac{-t}{RC}}.$$

Answer:
Make the exponential term the subject and then take the natural logarithms of both sides
$$
\begin{align}
V &= 1- e^{\frac{-t}{RC}}\\
e^{\frac{-t}{RC}} &= 1- v\\
\ln\left(e^{\frac{-t}{RC}}\right) &= \ln(1- v)\\
\frac{-t}{RC} &= \ln(1-v)\\
t &= -RC\ln(1-v)
\end{align}
$$


1. Show that the following hyperbolic identity holds:
    $$\cosh^2(x)-\sinh^2(x)=1.$$

Answer:
Use the definitions of $\cosh(x) = \frac{e^x + e^-x}{2}$ and $\sinh(x) = \frac{e^x - e^{-x}}{2}$
$$
\begin{align}
\cosh^2(x) - \sinh^2(x) &=(\cosh(x) + \sinh{x})(\cosh(x) - \sinh(x))\\
&=\left(\frac{e^x + e^{-x} + e^x - e^{-x}}{2}\right)\left(\frac{e^x + e^{-x} - e^x + e^{-x}}{2}\right)\\
&=e^x e^{-x}
&= 1 \text{ as required}
\end{align}
$$

