# Exercise Set 1 Answers {.unlisted .unnumbered}

These exercises cover the topics of Algebra, Equations and Inequalities.

1.  Simplify each of the following (*Hint*: use the rules of exponents where needed).
    a.  $3pq+5pr-2qr+qp-6rp$
    b.  $5l^2mn+2nl^2m-3mln^2+l^2nm+4n^2ml-nm^2$
    c.  $\dfrac{(s^\frac{1}{3})^\frac{3}{4}\times (t^\frac{1}{4})^{-1}}{(t^\frac{1}{2}\times (s^{-\frac{1}{4}})^{-1})}$

    Answers:

    a.  We collect the so-called "like terms" (if there are any):
    \begin{align*}
    &3pq + 5pr - 2qr + qp -6rp = 3pq +qp +5pr - 6rp - 2qr \\
    &= 4pq - pr - 2qr \quad\text{    we add and/or subtract ``like terms''} 
    \end{align*}

    b. We collect the so-called "like terms" (if there are any):
    \begin{align}
    &5l^2 mn + 2nl^2m - 3mln^2 + l^2nm + 4n^2ml - nm^2\\
    &= 5l^2 mn + 2nl^2m + l^2nm - 3mln^2 + 4n^2ml - nm^2\\
    &= 8l^2 mn + n^2lm - nm^2 \quad\text{ we add and/or subtract ``like terms''}
    \end{align}

    c. We first complete the calculation in both the numerator and the
    denominator using the laws of indices:
    \begin{align}
    &
    \frac{(s^\frac{1}{3})^\frac{3}{4} \times (t^\frac{1}{4})^{-1}}{(t^\frac{1}{2})^4 \times (s^{-\frac{1}{4}})^{-1}}=\frac{s^{\frac{1}{3}\times\frac{3}{4}}\times t^{-\frac{1}{4}}}{t^{\frac{1}{2} \times 4}\times s^{\frac{1}{4}}}\\
    &= \frac{s^\frac{1}{4}\times t^{-\frac{1}{4}}}{t^{\frac{1}{2}} \times s^\frac{1}{4}}\quad \text{we combine the powers of the same base together using laws of indices}\\
    &= s^{\frac{1}{4}-\frac{1}{4}} \times t^{-\frac{1}{4}-\frac{1}{2}} = 1 \times t^{-\frac{3}{4}} = \frac{1}{t^\frac{3}{4}}
    \end{align}

    It is best to write your final answer with positive exponents only.

2.  Expand the brackets in each of the following and simplify the expression.

    a.  $-4x(2x-y)(3x+2y)$
    b.  $(a-2b)(2a-3b)(3a-4b)$
    c.  $-\{-2[x-3(y-4)]-5(z+6)\}$
    d.  $(v^3-v^2-2)(1-3v+2v^2)$

    Answers:

    a. We have three factors. First we multiply $-4x$ by $2x-y$, then we multiply the outcome by $(3x + 2y)$.
    \begin{align*}
    -4x(2x-y)(3x+2y) &= (-8x^2 + 4xy)(3x+2y)\\
    & = -24x^3 - 4x^2y + 8xy^2.
    \end{align*}

    b. Again, we have three factors, we repeat the same process (make sure you simplify the outcome in each step, i.e. add/subtract like-terms):
    \begin{align*}
    (a-2b)(2a-3b)(3a-4b) &= (2a^2 - 3ab - 4ab + 6b^2)(3a - 4b)\\
    &= (2a^2 - 7ab + 6b^2)(3a - 4b)\\
    &= 6a^3 - 8a^2 b - 21a^2b + 28ab^2 + 18b^2a - 24b^3\\
    &= 6a^3 - 29a^2b + 46b^2a - 24b^3
    \end{align*}

    c. We calculate the inner brackets first, then we remove the brackets. Lastly, we add/subtract like terms:
    \begin{align*}
    -\{ -2[x - 3(y-4)]- 5(z+6)\} &= - \{-2[x - 3y + 12] - 5(z+6)\}\\
    &= - (-2x + 6y - 24 -5z -30)\\
    &= -(-2x + 6y -5z -54)\\
    &= 2x - 6y + 5z +54
    \end{align*}

    d.
    \begin{align*}
    (v^3 - v^2 - 2)(1 - 3v + 2v^2) &= v^3 - 3v^4 + 2v^5 - v^2 + 3v^3 - 2v^4 - 2 + 6v - 4v^2\\
    &= 2v^5 - 5v^4 + 4v^3 - 5v^2 + 6v - 2
    \end{align*}

3.  Simplify each of the following.

    a.  $\dfrac{p}{q^3}\div\dfrac{p^3}{q}$
    b.  $\dfrac{a^2b}{2c}\times\dfrac{ac^2}{2b}\div\dfrac{b^2c}{2a}$
    c.  $\dfrac{8x^{-3}\times 3x^2}{6x^{-4}}$
    d.  $\dfrac{3x}{3x^2+6x}$

    Answers:
    a.
    $$
    \frac{p}{q^3} \times \frac{q}{p^3} = \frac{pq}{q^3 p^3} = \frac{1}{p^2 q^2}
    $$

    b. We first multiply the first two fractions, then we divide the outcome by the third
    \begin{align*}
    \left(\frac{a^2 b}{2c} \times \frac{ac^2}{2b}\right)\div \frac{b^2c}{2a} &= \frac{a^3 b c^2}{4cb}\div \frac{b^2 c}{2a}\\
    &= \frac{a^3 b c^2}{4cb}\times \frac{2a}{b^2c}\\
    &= \frac{2a^4 b c^2}{4b^3 c^2} = \frac{a^4}{2b^2}
    \end{align*}

    c. 
    \begin{align*}
    \frac{8x^{-3} \times 3x^2}{6x^{-4}} &= \frac{24x^{-3+2}}{6x^{-4}}\\
    &= 4x^{-1+4}\\
    &= 4x^3
    \end{align*}

    d. 
    $$
    \frac{3x}{3x^2 + 6x} = \frac{3x}{3x(x+2)} = \frac{1}{x+2}
    $$

4.  Factorise the following expressions.

    a.  $18x^2y-12xy^2$
    b.  $x^3+4x^2y-3xy^2-12y^3$
    c.  $25x^2-4y^2$

    Answers:

    a. We look for the common factors between the two terms, in this case $6xy$
    $$
    18x^2y - 12xy^2 = 6xy(3x-2y)
    $$

    b. This expression has 4 terms, we divide them into 2 groups each of 2 terms, then factorise these groups and use the difference of two squares to factorise the term with squares
    \begin{align*}
    x^3 + 4x^2y - 3xy^2 - 12y^3 &= x^2(x+4y) - 3y^2(x+4y)\\
    &= (x+4y)(x^2-3y^2)\\
    &= (x+4y)(x-\sqrt{3}y)(x+\sqrt{3}y)
    \end{align*}
    
    c. This is another application of the difference between two squares identity $a^2 - b^2 = (a-b)(a+b)$
    $$
    25x^2 - 4y^2 = (5x+2y)(5x-2y)
    $$

4.  The characteristic equation of a perfect gas is given by $PV = mRT$
    where $m$ is the mass, $P$ is the pressure, $V$ is the volume, $T$
    is the temperature and $R$ is the universal gas constant. Make
    temperature the subject of the formula.

    Answer:

    $$PV = mRT$$
    Divide both sides by $mR$, then
    $$T = \frac{PV}{mR}$$

5.  The airflow over a turbine blade causes drag $D$, which is given by
    $D= \frac{\rho C v^2 A}{2}$, where $\rho$ is fluid density, $C$ is
    the drag coefficient, $v$ is fluid velocity and $A$ is the frontal
    area of the blade. Make the frontal area the subject of the formula.

    Answer:

    First multiply both sides by 2, then divide both sides of the outcome by $\rho C v^2$
    
    \begin{align*}
    D &= \frac{\rho C v^2 A}{2}\\
    2D &= \rho C v^2 A\\
    A &= \frac{2D}{\rho C v^2}
    \end{align*}
    


6.  Make $b$ the subject of the following formula.
    $$W=\frac{t\sqrt{a+b^2}}{2\pi}$$

    Answer:

    First, multiply both sides by $2\pi$ and divide both sides by $t$, then square both sides and make $b^2$ the subject

    \begin{align*}
    W &= \frac{t\sqrt{a + b^2}}{2\pi}\\
    \frac{2\pi W}{t} &= \sqrt{a+b^2}\\
    \left(\frac{2\pi W}{t}\right)^2 &= a + b^2\\
    b^2 &= \frac{4\pi^2 W^2}{t^2} - a
    \end{align*}

    Now it is necessary to take the square root of both sides, recalling that there is both a positive and a negative root:
    $$
    b = \pm \sqrt{\frac{4\pi^2 W^2}{t^2} - a}
    $$
    Often in applications such a quantity may have a physical significance that will force it to be only the positive root or only the negative root, for example if the quantity $b$ represented a length then we would take the positive solution.