# Exercise Set 6 {-}

These exercises cover the topic of vectors.

Note that the questions are independent of one another, so the definition of a vector $\mathbf{a}$ in one question does not carry over to another question with a vector called $\mathbf{a}$.

1. The points $A$, $B$ and $C$ have position vectors
    \begin{align*}
    \mathbf{a}&=5\mathbf{i}-6\mathbf{j}+4\mathbf{k}\\
    \mathbf{b}&=2\mathbf{i}+5\mathbf{j}-3\mathbf{k}\\
    \mathbf{c}&=-\mathbf{i}+4\mathbf{k}.
    \end{align*}
    Find:
    a. $5\mathbf{a}-2\mathbf{b}-3\mathbf{c}$
    a. $\overrightarrow{AC}+\overrightarrow{AB}$
    a. $\mathbf{a}\cdot\mathbf{b}$
    a. The angle between $\mathbf{a}$ and $\mathbf{b}$
    a. $\mathbf{a}\times\mathbf{c}$

1. Let $\mathbf{p}$ and $\mathbf{q}$ be vectors.
    a. What is the vector $\mathbf{r}$ joining the points whose position vectors are $\mathbf{p}$ and $2\mathbf{q}$?
    a. What is the vector $\mathbf{s}$ joing the points whose position vectors are $\mathbf{2q}$ and $-6\mathbf{p}+14\mathbf{q}$?
    a. What do you notice about $\mathbf{r}$ and $\mathbf{s}$?
    a. What does this tell you about the points whose position vectors are $\mathbf{p}$, $2\mathbf{q}$ and $-6\mathbf{p}+14{q}$?
    <!--- they are collinear, i.e. all lie in a straight line --->

1. Let $\mathbf{u}=5\mathbf{i}+2\mathbf{j}$ and $\mathbf{v}=3\mathbf{i}-\mathbf{j}-3\mathbf{k}$. Find $(4\mathbf{u}-6\mathbf{v})\cdot(2\mathbf{u}+3\mathbf{v})$.

1. Given that the position vectors of the points $A$, $B$, and $C$ are $\mathbf{a}$, $\mathbf{b}$ and $\mathbf{c}$, write down the position vectors of the midpoints of the lines $BC$ and $CA$.

1. Prove that the vector joining the midpoints of two sides of a triangle is parallel to the third side and half of its length.

1. Show that the vectors
    \begin{align*}
    \mathbf{a}&=8\mathbf{i}+2\mathbf{j}-3\mathbf{k}\\
    \mathbf{b}&=3\mathbf{i}-6\mathbf{j}+4\mathbf{k}
    \end{align*}
    are perpendicular to one another (Hint: use the dot product).

1. A block of mass $m=1\,\text{kg}$ is sliding down a frictionless slope under gravity. The slope is at an angle of $45^\circ$ to the horizontal. Recall that the force on the block is given by Newton's second law: $\mathbf{F}=m\mathbf{g}$ where $\mathbf{g}=-9.8\mathbf{k}\,\text{ms}^{-2}$ is the gravitational acceleration. Resolve the force vector in the directions parallel and perpendicular to the slope. (Hint: you need to project the force vector onto unit vectors that are parallel and perpendicular to the slope.)

1. Let
    $$\mathbf{a}=\begin{pmatrix}
    2\\
    -1\\
    3
    \end{pmatrix}
    ,\qquad
    \mathbf{b}=\begin{pmatrix}
    5\\
    1\\
    -4
    \end{pmatrix}.
    $$
    Show that $(\mathbf{a}-\mathbf{b})\times(\mathbf{a}+\mathbf{b})=2\mathbf{a}\times\mathbf{b}$.

1. Show that
    $$(\mathbf{a}+\mathbf{b})\cdot((\mathbf{b}+\mathbf{c})\times (\mathbf{c}+\mathbf{a}))=2\mathbf{a}\cdot(\mathbf{b}\times\mathbf{c}).$$
    The quantity $\mathbf{a}\cdot(\mathbf{b}\times\mathbf{c})$ is known as the [scalar triple product](https://en.wikipedia.org/wiki/Triple_product#Scalar_triple_product): its geometric interpretation is the volume of the parallelepiped defined by the three vectors.

1. Let
    $$\mathbf{a}=\begin{pmatrix}
    \alpha\\
    0\\
    -1
    \end{pmatrix}
    ,\qquad
    \mathbf{b}=\begin{pmatrix}
    3\\
    2\\
    5
    \end{pmatrix}
    ,\qquad
    \mathbf{c}=\begin{pmatrix}
    2\\
    -1\\
    4
    \end{pmatrix}.
    $$
    Find the values of $\alpha$ for which $\mathbf{a}\times\mathbf{b}$ is perpendicular to $\mathbf{a}\times\mathbf{c}$.

1. The *torque* is the rotational equivalent of linear force. It is given by the product of the magnitude of the force and the perpendicular distance of the line of action of a force from the axis of rotation. We can calculate torque using the cross product:
$$\boldsymbol\tau = \mathbf{r}\times \mathbf{F}$$
where $\boldsymbol\tau$ is the torque vector, $\mathbf{r}$ is the position vector (from the axis of rotation to the point where the force is applied) and $\mathbf{F}$ is the force vector.

    Find the torque about the point $\mathbf{i}+2\mathbf{j}-\mathbf{k}$ of a force $\mathbf{F}=3\mathbf{i}+\mathbf{k}$ acting on a particle at position $2\mathbf{i}-\mathbf{j}+3\mathbf{k}$.
