# Exercise Set 8 {.unlisted .unnumbered}

1. Find the first and second dervatives of the following expressions.
    a. $y=3x^5+2x-1$
    a. $y=4x^{-1}$
    a. $y=x^{\frac{1}{2}}+x^{\frac{1}{3}}$
    a. $y=x^7+\sin(x)$
    a. $y=e^x+5$

1. Find the derivative of $(1+2x)(x-x^2)$ in two ways: first, expand and find the derivative; second, use the product rule. Your answers should agree!

1. Use the product rule to show that $(af)'(x)=af'(x)$ for any differentiable function $f$ and number $a$.

1. Use the chain rule to show that $(f(ax+b))'=af'(ax+b)$ for any differentiable function $f$ and numbers $a$ and $b$.

1. Find the derivatives of the following functions (you may like to use the additional rules you have just derived in the previous two questions).
    a. $f(x)=\sqrt{2}\sin(x)$
    a. $f(x)=\ln(2)\ln(x)$
    a. $f(x)=\cos(3x)$
    a. $f(x)=\sin(5x+2)$
    a. $f(x)=3e^{2x}$
    a. $f(x)=3e^{2x+1}$

1. Find the derivatives of the following functions using the product rule.
    a. $f(x)=3x^2\sin(x)$
    a. $f(x)=\sin(x)\cos(x)$
    a. $f(x)=(x^3-x)e^x$
    a. $f(x)=x\ln(x)$

1. Find the derivatives of the following functions using the chain rule.
    a. $f(x)=\cos(x^2)$
    a. $f(x)=\sin(\cos(x))$
    a. $f(x)=e^{\sin(x)}$
    a. $f(x)=\sin^{100}(x)$

1. Find the derivatives of the following functions using the quotient rule.
    a. $f(x)=\dfrac{1}{1+x^2}$
    a. $f(x)=\dfrac{x^2}{1+x^2}$
    a. $f(x)=\dfrac{x^3}{e^{3x}}$
    a. $f(x)=\dfrac{x-\sqrt{x}}{x^2}$
    a. $f(x)=\dfrac{\sin(x)}{\cos(x)}$

1. Find the derivatives of the following functions.

    a. $f(x)=\sin^2(\sin(x))$
    a. $f(x)=\ln(x^2)$
    a. $f(x)=a^x$ for any $a>0$
    a. $f(x)=e^x\sin(x^2)$

    Answers:

    a. We recognise this as a composition of three functions $f(x)=s(t(u(x)))$ with
        $u(x)=\sin(x)$
        $t(x)=\sin(x)$
        $s(x)=x^2$
        First applying the chain rule to $s$ and $t$
        $$\frac{df(x)}{dx}=\frac{ds(t)}{dt}\frac{dt(u(x))}{dx}$$
        Then applying the chain rule to $t$ and $u$
        $$\frac{df(x)}{dx}=\frac{ds(t)}{dt}\left(\frac{dt(u)}{du}\frac{du(x)}{dx}\right)$$
        so we have
        $$\frac{df(x)}{dx}=2\sin(\sin(x))\times \cos(\sin(x))\times\cos(x).$$

    a. We could first turn the power into a product to obtain $f(x)=2\ln(x)$, then the derivative Is
        $$\frac{df(x)}{dx}=2\frac{1}{x}.$$

        Alternatively, we could use the chain rule. Letting $u(x)=x^2$ we have
        \begin{align*}
        \frac{df(x)}{dx}&=\frac{\ln(u)}{du}\frac{du(x)}{dx}\\
        &=\frac{1}{u}2x\\
        &=\frac{2x}{x^2}\\
        &=\frac{2}{x}.
        \end{align*}

    a. We can use the natural logarithm to obtain
        $$f(x)=e^{\ln(a^x)}=e^{x\ln(a)}.$$
        Then
        $$\frac{df(x)}{dx}=\ln(a)e^{x\ln(a)}=\ln(a)e^{\ln(a^x)}=\ln(a)a^x.$$

    a. We have $f(x)=s(x)t(u(x))$ with $s(x)=e^x$, $t(x)=\sin(x)$, $u(x)=x^2$. We have a product and a composition. First applying the product rule
        $$\frac{df(x)}{dx}=\frac{ds(x)}{dx}t(u(x))+s(x)\frac{dt(u(x))}{dx}.$$
        Then appying the chain rule
        $$
        \frac{df(x)}{dx}=\frac{ds(x)}{dx}t(u(x))+s(x)\frac{dt(u)}{du}\frac{du(x)}{dx}.$$
        So, we have
        \begin{align*}
        \frac{df(x)}{dx}&=e^x\sin(x^2)+e^x\cos(x^2)2x\\
        &=e^x(\sin(x^2)+2x\cos(x^2))
        \end{align*}


1. Show that $\frac{d}{dx}\sinh(x)=\cosh(x)$ and $\frac{d}{dx}\cosh(x)=\sinh(x)$.

    Answer:

    $\dfrac{d}{dx}\sinh(ax)=\dfrac{d}{dx}\dfrac{e^{ax}-e^{-ax}}{2}=\dfrac{ae^{ax}-(-a)e^{-ax}}{2}=a\dfrac{e^{ax}+e^{-ax}}{2}=a\cosh(ax)$
    and
    $\dfrac{d}{dx}\cosh(ax)=\dfrac{d}{dx}\dfrac{e^{ax}+e^{-ax}}{2}=\dfrac{ae^{ax}+(-a)e^{-ax}}{2}=a\dfrac{e^{ax}-e^{-ax}}{2}=a\sinh(ax)$.

1. Find all local maxima and minima of the following functions. Are there any global maxima or minima? Also sketch their graphs.
    a. $f(x)=x^2+3x+1$
    a. $f(x)=x^3-3x$

    Answer:
    
    For graph sketching we want to find the following:
    * Where the curve crosses the $x$-axis and $y$-axis.
    * The coordinates of any local maxima and minima.
    * The general shape of the curve.
    * Any asymptotes.

1. A particle moving in a straight line has displacement $x$ as a function of time $t\geq 0$ given by
    $$x=-t^{3}+5t^{2}+t.$$
    a. Find the velocity $v$ and acceleration $a$.
    a. What is the initial velocity?
    a. What is the largest positive displacement?
    a. At what time does the particle return to the origin?

1. Find the points of inflection of the following functions.
    a. $f(x)=\dfrac{x^3}{3}-\dfrac{x^2}{2}-2x+5$
    a. $f(x)=x+\sin(x)$

1. A rectangular box with no lid is made from a thin sheet of metal. The base is $2x\text{ mm}$ long and $x\text{ mm}$ wide, and the volume is $48000\text{ mm}^3$. Show that the area $A$ of metal used is given by
$$A=2x^2+144000x^{-1} \text{ mm}^2.$$
Find the value of $x$ for which the minimum area of metal is used along with the value of the minimum area.



