# Exercise Set 8 {-}


1. Write down the $2\times 2$ matrix $R_\pi$ that rotates a vector anticlockwise by $\pi$. Apply this to a vector $\mathbf{v}=\left(\begin{smallmatrix}v_1\\v_2\end{smallmatrix}\right)$.

1. Write down the $2\times 2$ matrix $M_x$ that reflects a vector in the $x$-axis. Similarly write down the $2\times 2$ matrix $M_y$ that reflects a vector in the $y$-axis. Multiply these two matrices to find the transformation that first reflects in the $x$-axis and then reflects in the $y$-axis. Compare this to the matrix $R_\pi$.

1. Note that $R^2_\theta=R_{2\theta}$ (why?). Use this to find the "double angle identity" for $\cos$ and $\sin$. Can you find other trigonometric identities using $R_\theta$?

1. For each of the following pairs of matrices $A$ and $B$, find (when possible), $A+B$, $A-B$, $A^2$, $B^2$, $AB$, $BA$.

	a. $A = \begin{pmatrix} 2 & 3 \\ 4 & 1 \end{pmatrix}\qquad B = \begin{pmatrix} -1 & 2 \\ -2 & 0 \end{pmatrix}$
	a. $A = \begin{pmatrix} 4 & -5 \\ 6 & 1 \\ 0 & 1 \end{pmatrix}\qquad B = \begin{pmatrix} 5 & 2 & -3 \\ 1 & 3 & -1 \\ 2 & 2 & -1 \end{pmatrix}$
	a. $A = \begin{pmatrix} 1 & 1 & 0 \\ 0 & 0 & 1\\ 1 & 0 & 1 \end{pmatrix} \qquad B = \begin{pmatrix} 0 & 0 & 1 \\ 1 & 0 & 0 \\ 1 & 1 & 0 \end{pmatrix}$
	a. $A = \begin{pmatrix} -1 & 1 & 0 & 1 \\ 1 & 0 & 1 & 1\\ 1 & 0 & 1 & 0\\ 1 & 1 & 1 & -1 \end{pmatrix} \qquad B = \begin{pmatrix} 0 & 0 & 1 \\ 1 & 0 & 0 \\ 1 & 1 & 0 \\ 1 & -1 & 1 \end{pmatrix}$.

1. Find two $3 \times 3$ matrices $A$ and $B$ such that $AB=BA$. Now find two $3 \times 3$ matrices such that $AB\neq BA$.

1. For any two numbers $a$ and $b$, if $ab=0$ then at least one of $a$ or $b$ must be $0$. Does an analagous result hold for matrices? That is, if $AB=0_{n\times m}$ must at least one of the matrices $A$ or $B$ be the zero matrix?

1. Determine whether the following matrices are *invertible* or *singular* by computing their determinants. If they are invertible, find the inverse.
    a. $\begin{pmatrix} 2 & 1 \\ 1 & 1 \end{pmatrix}$
    a. $\begin{pmatrix} 6 & 3 \\ -4 & -2 \end{pmatrix}$
    a. $\begin{pmatrix} 4 & -28 & 48 \\ -27 & 162 & -216 \\ 32 & -160 & 192 \end{pmatrix}$
    a. $\begin{pmatrix} \cos(\theta) & -\sin(\theta) \\ \sin(\theta) & \cos(\theta)\end{pmatrix}$
    a. $\begin{pmatrix} 1 & 3 & -5 \\ -2 & 1 & 4 \\ 1 & 2 & -4 \end{pmatrix}$
    a. $\begin{pmatrix} 1 & -1 & 4 \\ 2 &  3 & 3 \\ 3 &  1 & 8 \end{pmatrix}$


1. Find the eigenvalues and eigenvectors of each of the following matrices $A$. Determine whether the matrix is diagonalisable and, if so, find the matrices $D$ and $P$ in the diagonalisation $D=P^{-1}AP$.

    a. $\begin{pmatrix} 1 & 0 \\ 2 & 2 \end{pmatrix}$
    a. $\begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix}$
    a. $\begin{pmatrix} 1 & 2 \\ 2 & -2 \end{pmatrix}$
    a. $\begin{pmatrix} 1 & -2 & -1 \\ 2 & 6 & 2 \\ -1 & -2 & 1 \end{pmatrix}$
    a. $\begin{pmatrix} -2 & 1 & 1 \\ -11 & 4 & 5 \\ -1 & 1 & 0 \end{pmatrix}$
    a. $\begin{pmatrix} 2 & \sqrt 2 & 0 \\ \sqrt 2 & 2 & \sqrt 2 \\ 0 & \sqrt 2 & 2 \end{pmatrix}$
    a. $\begin{pmatrix} 1 & -1 & -1 \\ 1 & -1 & 0 \\ 1 & 0 & -1 \end{pmatrix}$
    a. $\begin{pmatrix} 5 & 5 & 1 \\ -2 & -1 & 0 \\ 1 & 1 & 1 \end{pmatrix}$.

1. For the matrices in a. and d. in the previous question, find a formula for $A^n$.

1. *Linear Difference Equations*. A population of Wildebeest can be classified into two life stages: juvenile and adult. Each year $60\%$ of the juveniles survive to become adults, adults give birth on average to $0.5$ juvelines and $70\%$ of adults survive the year. If there are $200$ juveniles and $200$ adults in one year, what is the long term population of juveniles and adults? What is the long term ratio of juveniles to adults? Hint: write this as a matrix equation and use diagonalisation (save some time and use a computer to find the eigenvalues and eigenvectors for this question).

    How about in the case when the adult survival rate increases to $80\%$? In this case also give the long term growth rate of the juvenile and adult populations. What happens in the case that the adult survival rate drops to $60\%$?
