# Exercise Set 10 {-}

1. Find $\dfrac{dy}{dx}$ for the following by implicit differentiation.

    a. $x^2y+3xy^3-x=3$
    a. $\sin(x^2y^2)=x$
    a. $xy^2=y+e^{xy}$

1. Consider the curve $x^2+3xy+y^2+2x-7=0$. Use implicit differentiation to find $\dfrac{dy}{dx}$ and hence compute the equation of the tangent at the point $(1,1)$.

1. Find the slope of the circle $x^2+y^2=25$ at the point $(-3,-4)$. Hence find the equations of the tangent and normal at that point.

1. Find $\dfrac{dy}{dx}$ and $\dfrac{d^2y}{dx^2}$ for the following by implicit differentiation.
    a. $y+\sin(y)=x$
    a. $x^2-xy+y^2=3$

1. Find $\dfrac{dy}{dx}$ and $\dfrac{d^2y}{dx^2}$ for the following parametric equations.
    a. $y=\cos(2t)$ and $x=\sin(t)$
    a. $y=\dfrac{3+2t}{1+t}$ and $x=\dfrac{2-3t}{1+t}$
    a. $y=3\sin(\theta)-\sin^3(\theta)$ and $x=\cos^3(\theta)$

1. Find the derivative of the following inverse functions by implicit differentiation.
    a. $y=\sin^{-1}(x)$
    a. $y=\cosh^{-1}(3x)$
    a. $y=\tan^{-1}(4x^2)$

1. Find $\dfrac{dy}{dx}$ for the following using logarithmic differentiation.
    a. $y=a^x$
    a. $y=\dfrac{(x-4)^7(2x+3)^2}{(4x+7)^3}$

1. Find $\dfrac{dy}{dx}$ for the following.
    a. $y=x^x$
    a. $y=(\tanh(x))^x$
    a. $x^3+\sin(xy)=xy^2$
