# Probability Distributions {.unlisted .unnumbered}


## Random Variables

A *random variable* is a numerical function whose inputs are elements of the sample space. It is said to be *discrete* if its outputs are in a finite set of values or a countable set of values. For the moment we stick to the discrete case, later we will look at *continuous* random variables.

::: {.example #randomcoin name="Coin tosses"}
A coin is tossed 3 times. Let the probability of getting a head be $p$ (not necessarily $p=\frac{1}{2}$ --- it could be a biased coin).

There are 8 possible outcomes. Let $X$ be a random variable whose output is the number of heads:

|**Sample**|**Probability**| $X$ |
|----------|---------------|-----|
|TTT|$(1-p)^3$ |0|
|TTH|$p(1-p)^3$|1|
|THT|$p(1-p)^3$|1|
|HTT|$p(1-p)^3$|1|
|THH|$p^2(1-p)$|2|
|HTH|$p^2(1-p)$|2|
|HHT|$p^2(1-p)$|2|
|HHH|$p^3$|3|

The convention is to denote a random variable using an upper-case letter and to denote a value that the random variable takes using a lower-case letter. For the above example, 

:::