# Exercise Set 12 {-}

1. Determine the following indefinite integrals
    a. $\int 2x^7\; dx$
    a. $\int 5x^2+2x-1 \; dx$
    a. $\int \sin(\theta)+\cos(\theta) \; d\theta$
    a. $\int 3e^t + \frac{2}{t} \; d t$
    a. $\int x^\frac{1}{2} \; dx$

1. Determine the following definite integrals
    a. $\int_0^2 x^2-2x\; dx$
    a. $\int_4^{16} \frac{2}{\sqrt{x}} \; dx$
    a. $\int_{-r}^r \frac{mx^2}{2r}\: dx$
    a. $\int_{-\frac{\pi}{2}}^\frac{\pi}{2}\cos(x)\; dx$
    a. $\int_{\ln(2)}^{\ln(3)} e^x\; dx$

1. Let $F(x)$ be an anti-derivative of $f(x)$. Find an anti-derivative of $f(ax+b)$ where $a$ and $b$ are constants. Hint: use the chain rule on $F(ax+b)$.

1. Use your result to the previous question to find the following indefinite integrals
    a. $\int (2x+6)^2\; dx$
    a. $\int (2x+6)^99 \; dx$
    a. $\int \sin(3x+2) \; dx$
    a. $\int \cos(-4x-1) \; dx$
    a. $\int \sec^2(9x+2) \; dx$
    a. $\int \frac{1}{2x+7}\; dx$
    a. $\int e^{-3x+1}\; dx$
    a. $\int \frac{1}{(5x+1)^2}\; dx$
    a. $\int \sqrt{3x+4}\; dx$

1. Find the area between the curve and the $x$-axis of the function $f(x)=x^3-x$ and the lines $x=0$ and $x=2$.

1. The velocity $v$ ($\text{ms}^{-1}$) of a particle moving in a straight line at time $t$ ($\text{s}$) is given by:
    $$v=6t^2-30t-36\quad t>0$$
    By integrating, find the distance travelled by the particle between $t=3$ and $t=5$ seconds.


1. The *Root Mean Square* (RMS) value of a signal over the interval $a$ to $b$ is defined as
    $$\left(\frac{1}{b-a}\int_{a}^{b} (f(x))^2 \; dx\right)^\frac{1}{2}$$
    Find the RMS of the voltage signal
    $$V(t)=3\sin(2t)+5\cos(4t)$$
    between $a=0$ and $b=2\pi$.

1. The *volume of revolution* of a curve is defined as
    $$\int_a^b \pi (f(x))^2 \; dx$$
    Find the volume of revolution of the curve
    $$f(x)=e^{-2x}$$
    between $a=1$ and $b=2$.

1. The points $(1,1)$ and $(2,8)$ on the curve $y=x^3$ are joined by a straight line. Calculate the area between the line and the curve.