# Exercise Set 15 {-}

1. You throw five fair dice and count the number of sixes you get. Let
$X$ be the number of sixes.
Tabulate $P(X=x)$ for $x=0, 1,\dots,5$.

1. A random variable $X$ has Poisson distribution with rate parameter $\lambda=2$. Find:
    a. $P(X \le 2)$
    a. $P(X=3)$
    a. $P(X \ge 4)$

1. A discrete random variable $X$ takes values in the set $\{1,2,3,4\}$
and has $P(X=x)=x/10$ for each $x$ in this set.
Find:
    a. $\operatorname{E}(X)$
    a. $\operatorname{E}(X^2)$
    a. $\operatorname{var}(X)$

1. A discrete random variable $X$ takes values in the set $\{1,2,3\}$
and has $P(X=x)=c/x$ for each $x$ in this set, where
$c$ is some suitable constant.
Find $c$ and so find
    a. $\operatorname{E}(X)$
    a. $\operatorname{E}(X^2)$
    a. $\operatorname{var}(X)$

1. You throw two fair dice. Let $X$ denote the sum of the two numbers
thrown. Find:
    a. $\operatorname{E}(X)$
    a. $\operatorname{E}(X^2)$
    a. $\operatorname{var}(X)$

1. 2% of packages produced by a packaging machine have defective seals. What is the probability that a batch will contain more than 2 defective packages if the batch size is (a) 20 (b) 50?

1. A rifle range competitor scores one hit in every 4 shots, on the average. Assuming that the binomial distribution is applicable, if they have four shots in a session what is:
    a. the probability that they will get exactly one hit?
    a. the probability that they will get at least one hit?

1. 2% of cans leaving a canning factory have a defective paint finish. Cans are packed in boxes in groups of 50. Determine the mean and standard deviation of:
    a. The number of cans in a box which have a defective finish.
    a. The proportion of cans in a box which have a defective coating.

1. Sheets of metal have a plating fault which occurs randomly at an average rate of 1 per $\text{m}^2$. What is the probability that a sheet $1.5\text{m} \times 2 \text{m}$ will have:
    a. At most one fault?
    a. At least one fault?

1. 250 litres of water have been polluted with 106 bacteria. What is the probability that a sample of 1 ml of the water contains no bacteria?

1. An average of 264 vehicles an hour pass along a stretch of road each taking 30 seconds to travel along it. What is the probability that at a given instant there will be no vehicles in the road?

