# Exercise Set 13 {-}

1. Using the method of separation of variables, find the general solutions of the following first order differential equations and the particular solutions in those cases where initial conditions are specified:

    a. $\displaystyle x^2\frac{dy}{dx}=(y+xy)$
    a. $\displaystyle \frac{dy}{dx}=\frac{y-1}{x-1},\; y(2)=3$
    a. $\displaystyle \frac{dy}{dx}=\frac{y+2}{x-2}$

1. Using the integrating factor method, find the general solutions of the following linear first order differential equations and the particular solutions in those cases where initial conditions are specified:

    a. $\displaystyle \frac{dy}{dx}+\frac{3}{x}y=4+x^2,\;y(1)=1$
    a. $\displaystyle x\frac{dy}{dx}+2y=x^{-4},\;y(1)=-\frac{1}{2}$
    a. $\displaystyle \frac{dy}{dx}+\frac{y}{x}=\cos(x),\;y\left(\frac{\pi}{2}\right)=0$
    a. $\displaystyle \frac{dy}{dx}=e^{-x}-2y,\;y(0)=0$
    a. $\displaystyle \frac{dy}{dx}=y\tan(x)+\sin(x)$

1. Find the general solutions of the following constant coefficient, linear, homogeneous differential equations, and the particular solutions in those cases where initial conditions are specified:

    a. $\displaystyle \frac{d^2y}{dx^2}+5\frac{dy}{dx}+6y=0,\;y(0)=0,\; \frac{dy(0)}{dx}=1$
    a. $\displaystyle \frac{d^2y}{dx^2}+8\frac{dy}{dx}+25y=0,\;y(0)=1,\; \frac{dy(0)}{dx}=0$
    a. $\displaystyle \frac{d^2y}{dx^2}+2\frac{dy}{dx}+y=0$

1. For each of the following differential equations, find: the Complementary Function; a Particular Integral; and the Particular Solution corresponding to the given initial conditions:

    a. $\displaystyle \frac{d^2y}{dx^2}+\frac{dy}{dx}+y=36e^{5x}$
    a. $\displaystyle \frac{d^2y}{dx^2}+3\frac{dy}{dx}-4y=-34\sin(x)$
    a. $\displaystyle \frac{d^2y}{dx^2}+3\frac{dy}{dx}-4y=24e^{-x},\;y(0)=0,\; \frac{dy(0)}{dx}=10$
    a. $\displaystyle \frac{d^2y}{dx^2}-3\frac{dy}{dx}+2y=x^2-2x+3,\;y(0)=\frac{3}{4},\; \frac{dy(0)}{dx}=\frac{3}{2}.$
