# Exercise Set 18 {-}

1. The following table contains students' exam marks.

    |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
    |---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
    |75|85|59|73|88|65|60|86|72|63|78|61|75|78|74|67|
    |60|68|74|66|82|78|94|73|71|83|79|96|67|62|75|81|
    |75|71|65|79|73|80|78|72|74|53|76|65|73|67|72|63|

    a. Create a frequency distribution table with classes 50-59, 60-69,... etc.
    a. Draw a histogram from the table.


1. The following table shows the results of 178 measurements of the carbon content of a mixed powder fed to a plant over a period of one month.

    |Range of values of Carbon (%)| Frequency|
    |---|---|
    |4.10-4.19 |1|
    |4.20-4.29 |2|
    |4.30-4.39 |7|
    |4.40-4.49 |20|
    |4.50-4.59 |24|
    |4.60-4.69 |31|
    |4.70-4.79 |38|
    |4.80-4.89 |24|
    |4.90-4.99 |21|
    |5.00-5.09 |7|
    |5.10-5.19 |3|
    |**Total** |**178**|

    From this frequency distribution, construct:
    a. a histogram
    a. a frequency polygon
    a. an ogive

    From the ogive, estimate the percentage of measurements showing a carbon content below 5.00%.

1. The following numbers are the marks obtained by 50 students in an
examination:

    |   |   |   |   |   |   |   |   |   |   |
    |---|---|---|---|---|---|---|---|---|---|
    | 57| 60| 37| 74| 62| 40| 56| 59| 80| 60|
    | 62| 94| 78| 73| 56| 68| 67| 79| 83| 87|
    | 90| 93| 58| 46| 77| 63| 66| 66| 56| 71|
    | 51| 77| 53| 69| 70| 69| 70| 70| 47| 54|
    | 49| 54| 68| 35| 64| 67| 76| 73| 68| 61|

    a. Reduce these marks to a frequency distribution, with equal class widths, having as the first interval 35-44 inclusive. Draw an ogive for the distribution.
    a. Using the graph, what is the median mark?
    c. Use your graph to estimate what % of students pass the examination if the pass mark is 55. 

1. A sample of underweight babies was fed a special diet and the following weight gains (lbs) were observed at the end of three months: 6.7, 2.7, 2.5, 3.6, 3.4, 4.1, 4.8, 5.9, 8.3. What are the mean and standard deviation?

1.  In an examination, the marks awarded to the first 40 scripts were:

    32, 57, 43, 65, 28, 60, 47, 52, 39, 48, 25, 53, 47, 52, 62, 31, 38, 46, 72, 51, 29, 45, 54, 48, 50, 66, 63, 36, 23, 43, 32, 39, 58, 55, 29, 48, 37, 43, 54, 40.

    a. Taking classes 14.5-24.5, 24.5-34.5, 34.5-44.5 etc, draw up a frequency distribution table for the marks. Also estimate the relative frequency, cumulative frequency and relative cumulative frequency.
    a. Draw a histogram, frequency polygon and ogive for this frequency distribution.
    a. From the frequency table, estimate the mean, variance and standard deviation of the marks.

1. A city has been criticized for its excessive discharges of untreated sewage into the nearby river. A microbiologist take 45 samples of water downstream from the treated sewage outlet and measures the number of bacteria present. A summary table is as follows:

    | Number of Bacteria | Number of Samples |
    |---|---|
    |20-30| 5|
    |30-40|20|
    |40-50|15|
    |50-60| 5|

    What are the $25^{\text{th}}$ and $75^{\text{th}}$ percentiles?